3_blp_server_16_03_2020/src/Entity/Catalog.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CatalogRepository")
 * @Vich\Uploadable
 */
class Catalog
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups("main")
     * @Groups("full")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("main")
     * @Groups("full")
     */
    private $title;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_active;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     * @Groups("main")
     */
    private $is_new;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     * @Groups("main")
     */
    private $is_sale;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups("full")
     */
    private $anonce;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups("full")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categories", inversedBy="catalogs")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("main")
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Productions", inversedBy="catalogs")
     * @Groups("full")
     */
    private $productions;


    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="catalog_image", fileNameProperty="imageName")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Groups("full")
     * @Groups("main")
     * @var string|null
     */
    private $imageName;


    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("main")
     * @Groups("full")
     */
    private $packing;

    /**
     * @ORM\Column(type="integer")
     * @Groups("main")
     * @Groups("full")
     */
    private $price;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getIsNew(): ?bool
    {
        return $this->is_new;
    }

    public function setIsNew(?bool $is_new): self
    {
        $this->is_new = $is_new;

        return $this;
    }

    public function getIsSale(): ?bool
    {
        return $this->is_sale;
    }

    public function setIsSale(?bool $is_sale): self
    {
        $this->is_sale = $is_sale;

        return $this;
    }

    public function getAnonce(): ?string
    {
        return $this->anonce;
    }

    public function setAnonce(?string $anonce): self
    {
        $this->anonce = $anonce;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCategory(): ?Categories
    {
        return $this->category;
    }

    public function setCategory(?Categories $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getProductions(): ?Productions
    {
        return $this->productions;
    }

    public function setProductions(?Productions $productions): self
    {
        $this->productions = $productions;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getPacking(): ?string
    {
        return $this->packing;
    }

    public function setPacking(string $packing): self
    {
        $this->packing = $packing;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
}

3_blp_server_16_03_2020/src/Form/CatalogType.php
<?php

namespace App\Form;

use App\Entity\Catalog;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;

class CatalogType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('is_active')
            ->add('is_new')
            ->add('is_sale')
            ->add('anonce')
            ->add('packing')
            ->add('price', MoneyType::class, [
                'currency' => 'RUB',
                'divisor' => 100,
            ])
            ->add('content')
            ->add('category')
            ->add('productions')
            ->add('imageFile', VichImageType::class, ['required' => false])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Catalog::class,
        ]);
    }
}

3_blp_server_16_03_2020/src/Controller/CatalogController.php
<?php

namespace App\Controller;

use App\Entity\Catalog;
use App\Form\CatalogType;
use App\Repository\CatalogRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("admin/catalog")
 */
class CatalogController extends AbstractController
{
    /**
     * @Route("/", name="catalog_index", methods={"GET"})
     */
    public function index(CatalogRepository $catalogRepository): Response
    {

        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        return $this->render('catalog/index.html.twig', [
            'catalogs' => $catalogRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="catalog_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $catalog = new Catalog();
        $form = $this->createForm(CatalogType::class, $catalog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($catalog);
            $entityManager->flush();
            return $this->redirectToRoute('catalog_index');
        }

        return $this->render('catalog/new.html.twig', [
            'catalog' => $catalog,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="catalog_show", methods={"GET"})
     */
    public function show(Catalog $catalog): Response
    {
        return $this->render('catalog/show.html.twig', [
            'catalog' => $catalog,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="catalog_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Catalog $catalog): Response
    {
        $form = $this->createForm(CatalogType::class, $catalog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('catalog_index');
        }

        return $this->render('catalog/edit.html.twig', [
            'catalog' => $catalog,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="catalog_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Catalog $catalog): Response
    {
        if ($this->isCsrfTokenValid('delete'.$catalog->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($catalog);
            $entityManager->flush();
        }

        return $this->redirectToRoute('catalog_index');
    }
}

3_blp_server_16_03_2020/templates/catalog/_delete_form.html.twig
<form method="post" action="{{ path('catalog_delete', {'id': catalog.id}) }}" onsubmit="return confirm('Вы уверены, что хотите удалить этот элемент?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ catalog.id) }}">
    <button class="btn btn-secondary">Удалить</button>
</form>

3_blp_server_16_03_2020/templates/catalog/_form.html.twig
{{ form_start(form,  {'attr':{'class': "card"}}) }}
<div class="card-header">
    <h4 class="card-title">{{ title_label|default('Новый элемент') }}</h4>
</div>

<div class="card-body">
    <div class="row">
        <div class="col-12">

            <div class="mb-3">
            {{ form_label(form.title, null, {
                'label': 'Название',
                'label_attr': {'class': 'form-label'}
            }) }}
            {{ form_widget(form.title, { 'attr': {'class': 'form-control'} }) }}
            </div>
            <div class="mb-3">
                <label class="form-check form-check-inline">
                    {{ form_widget(form.is_active, { 'attr': {'class': 'form-check-input'} }) }}
                    <span class="form-check-label">Активность</span>
                </label>
                <label class="form-check form-check-inline">
                    {{ form_widget(form.is_new, { 'attr': {'class': 'form-check-input'} }) }}
                    <span class="form-check-label">Новинка</span>
                </label>
                <label class="form-check form-check-inline">
                    {{ form_widget(form.is_sale, { 'attr': {'class': 'form-check-input'} }) }}
                    <span class="form-check-label">Возможна скидка</span>
                </label>
            </div>
            <div class="mb-3">
                {{ form_label(form.category, null, {
                    'label': 'Категория',
                    'label_attr': {'class': 'form-label'}
                }) }}
                {{ form_widget(form.category, { 'attr': {'class': 'form-select'} }) }}
            </div>
            <div class="mb-3">
                {{ form_label(form.productions, null, {
                    'label': 'Производитель',
                    'label_attr': {'class': 'form-label'}
                }) }}
                {{ form_widget(form.productions, { 'attr': {'class': 'form-select'} }) }}
            </div>
            <div class="mb-3">
                {{ form_label(form.anonce, null, {
                    'label': 'Анонс',
                    'label_attr': {'class': 'form-label'}
                }) }}
                {{ form_widget(form.anonce, { 'attr': {'class': 'form-control'} }) }}
            </div>
            <div class="mb-3">
                {{ form_label(form.packing, null, {
                    'label': 'Фасовка',
                    'label_attr': {'class': 'form-label'}
                }) }}
                {{ form_widget(form.packing, { 'attr': {'class': 'form-control'} }) }}
            </div>
            <div class="mb-3">
                {{ form_label(form.price, null, {
                    'label': 'Цена',
                    'label_attr': {'class': 'form-label'}
                }) }}
                {{ form_widget(form.price, { 'attr': {'class': 'form-control'} }) }}
            </div>
            <div class="mb-3">
                {{ form_label(form.imageFile, null, {
                    'label': 'Изображение материала',
                    'label_attr': {'class': 'form-label'}
                }) }}
                {{ form_widget(form.imageFile, { 'attr': {'class': 'form-control'} }) }}
            </div>
            <div class="mb-3">
                {{ form_label(form.content, null, {
                    'label': 'Полное описание',
                    'label_attr': {'class': 'form-label'}
                }) }}
                {{ form_widget(form.content, { 'attr': {'class': 'form-control editor'} }) }}
            </div>
        </div>
    </div>
</div>
<div class="card-footer text-right">
    <div class="d-flex">
        <a href="{{ path('catalog_index') }}" class="btn btn-link">Отмена</a>
        <button class="btn btn-primary ml-auto">{{ button_label|default('Сохранить') }}</button>
    </div>
</div>

{{ form_end(form) }}

3_blp_server_16_03_2020/templates/catalog/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
   {{ include('catalog/_form.html.twig', {'button_label': 'Обновить', 'title_label': 'Редактировать'}) }}
{% endblock %}

3_blp_server_16_03_2020/templates/catalog/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="page-header">
        <div class="row align-items-center">
            <div class="col-auto">
                <h2 class="page-title">
                    Каталог материалов
                </h2>
            </div>
        </div>
    </div>
<div class="card">
    <div class="card-header d-print-none">
        <h3 class="card-title"></h3>
        <div class="card-options">
            <a href="{{ path('catalog_new') }}" class="btn btn-primary">Добавить</a>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Н</th>
                <th>Название</th>
                <th>Цена</th>
                <th>Категория</th>
                <th>Выводить на сайт</th>
                <th>Новинка</th>
                <th>Возможна скидка</th>
                <th>Действия</th>

            </tr>
        </thead>
        <tbody>
        {% for catalog in catalogs %}
            <tr>
                <td>{{ catalog.id }}</td>
                <td>  <img class="catalog-img" src="{{ vich_uploader_asset(catalog, 'imageFile') }}" alt=""></td>
                <td>{{ catalog.title }}</td>
                <td>{{ catalog.price /100}}</td>
                <td>{{ catalog.category }}</td>
                <td>{{ catalog.isActive ? '<span class="badge bg-green">да</span>' : 'НЕТ' }}</td>
                <td>{{ catalog.isNew ? '<span class="badge bg-green">да</span>' : 'НЕТ' }}</td>
                <td>{{ catalog.isSale ? '<span class="badge bg-green">да</span>' : 'НЕТ' }}</td>

                <td>
                    <div class="btn-list">
                    <a href="{{ path('catalog_edit', {'id': catalog.id}) }}" class="btn btn-secondary">Редактировать</a>
                    {{ include('catalog/_delete_form.html.twig') }}
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">Нет ни одного материала</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
        </div>
    </div>
</div>


{% endblock %}

3_blp_server_16_03_2020/templates/catalog/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="page-header">
    <div class="row align-items-center">
        <div class="col-auto">
            <h2 class="page-title">
                Добавить материал
            </h2>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        {{ include('catalog/_form.html.twig') }}
    </div>
</div>




{% endblock %}

3_blp_server_16_03_2020/templates/catalog/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalog{% endblock %}

{% block body %}
    <h1>Catalog</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ catalog.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ catalog.title }}</td>
            </tr>
            <tr>
                <th>Is_active</th>
                <td>{{ catalog.isActive ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_new</th>
                <td>{{ catalog.isNew ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_sale</th>
                <td>{{ catalog.isSale ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Anonce</th>
                <td>{{ catalog.anonce }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ catalog.content }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('catalog_index') }}">back to list</a>

    <a href="{{ path('catalog_edit', {'id': catalog.id}) }}">edit</a>

    {{ include('catalog/_delete_form.html.twig') }}
{% endblock %}